default:
  image: docker:19.03.12


services:
  - docker:19.03.12-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - echo "User $CI_USER , Password $CI_PASSWORD"
    - docker login  -u  "$CI_USER" -p "$CI_PASSWORD"
    - docker buildx create --use
    - docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 -t jmmirand/node-app-test-hello-world:latest-gitlab .
#    - docker push jmmirand/node-app-test-hello-world:latest-gitlab
