default:
  image: ruby:2.5
  before_script:
    - apt-get update
    - apt-get install -y sqlite3 libsqlite3-dev nodejs
    - ruby -v
    - which ruby
    - gem install bundler --no-document

rspec:
  script:
    - ls -lrt

rubocop:
  script:
    - echo "job rubocop"
