default:
#  image: docker:19.03.12
  image: docker:stable

services:
  - docker:19.03.12-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - echo "User $CI_USER , Password $CI_PASSWORD"
    - docker login  -u  "$CI_USER" -p "$CI_PASSWORD"
    - docker build --platform linux/amd64 -t jmmirand/node-app-test-hello-world:latest-gitlab .
    - docker push jmmirand/node-app-test-hello-world:latest-gitlab
    - docker build --platform linux/arm64/v8 -t jmmirand/node-app-test-hello-world:latest-gitlab .
    - docker push jmmirand/node-app-test-hello-world:latest-gitlab


