default:
  image: docker:19.03.12


services:
  - docker:19.03.12-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t jmmirand/node-app-test-hello-world:latest .
