default:
#  image: docker:19.03.12
  image: docker:stable

services:
  - docker:19.03.12-dind

before_script:
  - docker info
  - apk add curl make
  - mkdir -vp ~/.docker/cli-plugins/ ~/dockercache
  - curl --silent -L "https://github.com/docker/buildx/releases/download/${BUILDX_VER}/buildx-${BUILDX_VER}.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker run --rm --privileged hypriot/qemu-register
  - cat  ~/.docker/config.json
  - docker buildx create --use
  - docker context create old-style
  - docker buildx create old-style --use


build:
  stage: build
  script:
    - echo "User $CI_USER , Password $CI_PASSWORD"
    - docker login  -u  "$CI_USER" -p "$CI_PASSWORD"
 #   - docker build --platform linux/amd64 -t jmmirand/node-app-test-hello-world:latest-gitlab .
 #   - docker push jmmirand/node-app-test-hello-world:latest-gitlab
 #   - docker build --platform linux/arm64/v8 -t jmmirand/node-app-test-hello-world:latest-gitlab .
 #   - docker push jmmirand/node-app-test-hello-world:latest-gitlab
    - docker buildx build --push --build-arg CI_NAME=local --platform linux/arm/v7,linux/arm64/v8,linux/386,linux/amd64 -t jmmirand/node-app-test-hello-world:latest-gitlab .
