default:
  image: docker:19.03.12


services:
  - docker:19.03.12-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t jmmirand/node-app-test-hello-world:latest-gitlab .
    - echo "User  $CI_USER , Password $CI_PASSWORD"
    - docker login -u "$CI_USER" -p "$CI_PASSWORD"
    - docker push jmmirand/node-app-test-hello-world:latest-gitlab
